fragment alleleFields on Allele {
  symbol
  fbalId
  isConstruct
  propagateTransgenicUses
  geneIsRegulatoryRegion
  stocksCount
  pubCount
  knownLesion
  hasImage
  alleleClasses {
    nodes {
      fbcvId
      name
    }
  }
  alleleMutagens {
    nodes {
      fbcvId
      name
    }
  }
  insertions {
    nodes {
      fbtiId
      symbol
      constructs {
        nodes {
          fbtpId
          symbol
          toolUses {
            nodes {
              ...toolUses
            }
          }
          tools {
            nodes {
              ...toolFields
            }
          }
        }
      }
    }
  }
  constructs {
    nodes {
      fbtpId
      symbol
      tools {
        nodes {
          ...toolFields
        }
      }
      toolUses {
        nodes {
          ...toolUses
        }
      }
    }
  }
  tools {
    nodes {
      ...toolFields
    }
  }
  toolUses {
    nodes {
      ...toolUses
    }
  }
}
