#import "./ToolFields.gql"
query InsertionsWithoutAllelesByGene($fbgn: String!) {
  genes(condition: { uniquename: $fbgn }) {
    nodes {
      name
      uniquename
      insertions {
        nodes {
          fbtiId
          symbol
          stocksCount
          pubCount
          constructs {
            nodes {
              fbtpId
              symbol
              toolUses {
                nodes {
                  ...toolUses
                }
              }
              tools {
                nodes {
                  ...toolFields
                }
              }
            }
          }
        }
      }
    }
  }
}
